=== andrei2timo/TwinCities/DSA-Twin-Cities/data/cities.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="twinning">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="image"/>
                <xs:element ref="description"/>
                <xs:element ref="description_source"/>
                <xs:element ref="cities"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="cities">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="city"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="city">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="name"/>
                <xs:element ref="country"/>
                <xs:element ref="country_code"/>
                <xs:element ref="latitude"/>
                <xs:element ref="longitude"/>
                <xs:element ref="description"/>
                <xs:element ref="description_source"/>
                <xs:element ref="population"/>
                <xs:element ref="area"/>
                <xs:element ref="currency"/>
                <xs:element ref="population_density"/>
                <xs:element ref="website"/>
                <xs:element ref="wiki"/>
                <xs:element ref="google_maps"/>
                <xs:element ref="image"/>
                <xs:element ref="image_alt"/>
                <xs:element ref="weather"/>
                <xs:element ref="places_of_interest"/>
            </xs:sequence>
            <xs:attribute name="woeid" use="required" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="country" type="non_null_string"/>
    <xs:element name="country_code">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:length value="3"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="population" type="xs:integer"/>
    <xs:element name="area" type="xs:decimal"/>
    <xs:element name="currency" type="non_null_string"/>
    <xs:element name="population_density" type="xs:decimal"/>
    <xs:element name="google_maps" type="non_null_URI"/>
    <xs:element name="weather">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="current_weather"/>
                <xs:element ref="forecast_weather"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="weather">
        <xs:sequence>
            <xs:element ref="temperature"/>
            <xs:element ref="humidity"/>
            <xs:element ref="wind_speed"/>
            <xs:element ref="wind_direction"/>
            <xs:element ref="icon"/>
            <xs:element ref="description"/>
            <xs:element ref="weather_time"/>
            <xs:element ref="weather_saved"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="current_weather" type="weather"/>
    <xs:element name="forecast_weather" type="weather"/>

    <xs:element name="places_of_interest">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="place_of_interest"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="place_of_interest">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="name"/>
                <xs:element ref="address"/>
                <xs:element ref="capacity"/>
                <xs:element ref="latitude"/>
                <xs:element ref="longitude"/>
                <xs:element ref="website"/>
                <xs:element ref="wiki"/>
                <xs:element ref="description"/>
                <xs:element ref="description_source"/>
                <xs:element ref="short_description"/>
                <xs:element ref="image"/>
                <xs:element ref="image_alt"/>
                <xs:element ref="map_icon"/>
            </xs:sequence>
            <xs:attribute name="category" use="required"/>
            <xs:attribute name="P_ID" use="required" type="xs:integer"/>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="non_null_string">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="non_null_URI">
        <xs:restriction base="xs:anyURI">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="address" type="non_null_string"/>
    <xs:element name="capacity" type="xs:string"/>
    <xs:element name="short_description" type="non_null_string"/>
    <xs:element name="map_icon" type="xs:NCName"/>
    <xs:element name="image" type="xs:anyURI"/>
    <xs:element name="description" type="non_null_string"/>
    <xs:element name="description_source" type="non_null_URI"/>
    <xs:element name="name" type="non_null_string"/>
    <xs:element name="latitude" type="xs:decimal"/>
    <xs:element name="longitude" type="xs:decimal"/>
    <xs:element name="website" type="xs:anyURI"/>
    <xs:element name="wiki" type="xs:anyURI"/>
    <xs:element name="image_alt" type="non_null_string"/>
    <xs:element name="temperature" type="xs:decimal"/>
    <xs:element name="humidity" type="xs:integer"/>
    <xs:element name="wind_speed" type="xs:decimal"/>
    <xs:element name="wind_direction" type="xs:decimal"/>
    <xs:element name="icon" type="non_null_string"/>
    <xs:element name="weather_time" type="xs:integer"/>
    <xs:element name="weather_saved" type="xs:integer"/>
</xs:schema>

=== andrei2timo/TwinCities/DSA-TwinCities/data/cities.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

#####################################################################
# file    : cities.xml                                              #
# purpose : xml data refactoring                                    #
# cities  : Torbay & Hamelin (Cities)                               #
#####################################################################
TODO: move poi into cities
-->
<twinning xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cities.xsd">
    <image>../images/banner.png</image>
    <description>Torbay has a historic link with Hamelin -
        there is evidence that both cities were founded over 1,000 years ago. 
		Fossils dating back to the Paleolithic have been found in Torbay, 
		and in Hamelin since 800 B.C., while there was a monastery.</description>
    <description_source>https://www.visitsouthdevon.co.uk/places/torquay-p2867463</description_source>

    <cities>
        <city woeid="3991">
            <name>Torbay</name>
            <country>United Kingdom</country>
            <country_code>GBR</country_code>
            <latitude>50.4523</latitude>
            <longitude>-3.5568</longitude>
            <description>Torbay is a borough in Devon, England, administered by the unitary authority of Torbay Council. It consists of 62.87 square kilometres (24.27 sq mi) of land, spanning the towns of Torquay, Paignton and Brixham, against an east-facing natural harbour Tor Bay of the Lyme Bay sheltered part of the English Channel.</description>
            <description_source>https://en.wikipedia.org/wiki/Torbay</description_source>
            <population>130959</population>
            <area>24.27</area>
            <currency>Pound Sterling (GBP)</currency>
            <population_density>1140</population_density>
            <website>https://www.torbay.gov.uk/</website>
            <wiki>https://en.wikipedia.org/wiki/Torbay</wiki>
            <google_maps>https://www.google.co.uk/maps/place/Torbay/</google_maps>
            <image>https://www.torbay.gov.uk/media/13501/torre-abbey-banner.jpg</image>
            <image_alt>Ariel shot of Torbay.</image_alt>
            <weather>
                <current_weather>
                    <temperature>275.48</temperature>
                    <humidity>93</humidity>
                    <wind_speed>10.8</wind_speed>
                    <wind_direction>310</wind_direction>
                    <icon>10d</icon>
                    <description>light rain</description>
                    <weather_time>1618910370</weather_time>
                    <weather_saved>1618910372</weather_saved>
                </current_weather>
                <forecast_weather>
                    <temperature>275.24</temperature>
                    <humidity>92</humidity>
                    <wind_speed>11.61</wind_speed>
                    <wind_direction>293</wind_direction>
                    <icon>04d</icon>
                    <description>overcast clouds</description>
                    <weather_time>1618920000</weather_time>
                    <weather_saved>1618910372</weather_saved>
                </forecast_weather>
            </weather>
			
            <places_of_interest>
                <place_of_interest P_ID="1" category="Village">
                    <name>Babbacombe model village</name>
                    <address> Hampton Ave, Babbacombe, Torquay TQ1 3LA, United Kingdom</address>
                    <capacity/>
                    <latitude>50.482466</latitude>
                    <longitude>-3.520361</longitude>
                    <website>https://www.model-village.co.uk/</website>
                    <wiki>https://en.wikipedia.org/wiki/Babbacombe_Model_Village</wiki>
                    <description>A 57 year old miniature village with over 400 individual models, with architecture ranging from Medieval to Victorian. This miniature marvel is encased by Babbacombe''s award winning gardens, spanning 4.5 acres.</description>
                    <description_source>https://www.englishriviera.co.uk/things-to-do/babbacombe-model-village-p142123</description_source>
                    <short_description>A 57-year-old model village.</short_description>
                    <image>https://media-cdn.tripadvisor.com/media/photo-s/0b/87/c3/2f/this-is-how-mesmerising.jpg</image>
                    <image_alt>Ariel shot of the village showing the gardens and landscape.</image_alt>
                    <map_icon>sight.png</map_icon>
                </place_of_interest>
                
				<place_of_interest P_ID="2" category="Cavern">
                    <name>Kents Cavern</name>
                    <address>91 Ilsham Rd, Torquay TQ1 2JF, United Kingdom</address>
				    <capacity/>
                    <latitude>50.46786</latitude>
                    <longitude>-3.504109</longitude>
                    <website>https://www.kents-cavern.co.uk/</website>
                    <wiki>https://en.wikipedia.org/wiki/Kents_Cavern</wiki>
                    <description>A labyrinth once occupied first by Neanderthals and some of the very first British populace. The caves are part of the English Riviera UNESCO Global Geopark and is known as one of Britain's oldest known prehistoric sites. Within the cave system, visitors can view prehistoric fossils and cave formations.</description>
                    <description_source>https://en.wikipedia.org/wiki/Kents_Cavern</description_source>
                    <short_description>A prehistoric cave system.</short_description>
                    <image>https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Torquay2.jpg/330px-Torquay2.jpg</image>
                    <image_alt>Interior view of Kent's Cavern.</image_alt>
                    <map_icon>cave.png</map_icon>
                </place_of_interest>
				
                <place_of_interest P_ID="3" category="Museum">
                    <name>Torre Abbey museum</name>
                    <address>The King's Drive, Torquay TQ2 5JE, United Kingdom</address>
                    <capacity>200</capacity>
                    <latitude>50.4627101</latitude>
                    <longitude>-3.5411543</longitude>
                    <website>https://www.torre-abbey.org.uk/</website>
                    <wiki>https://en.wikipedia.org/wiki/Torre_Abbey</wiki>
                    <description>Torbay's most historic building dating back to 1196, encased within garden and parkland spanning across 18 acres. The historic building also hosts a multi-award wining art collection with over 600 works of art from the 18th century to the present day.</description>
                    <description_source>https://en.wikipedia.org/wiki/Torre_Abbey</description_source>
                    <short_description>A 450 acre country park.</short_description>
                    <image>https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Torre_Abbey_side_entrance3.jpg/330px-Torre_Abbey_side_entrance3.jpg</image>
                    <image_alt>Torre Abbey, side entrance</image_alt>
                    <map_icon>historical_museum.png</map_icon>
                </place_of_interest>
				
				<place_of_interest P_ID="4" category="Museum">
                    <name>Cockington Court</name>
                    <address>Cockington Ln, Torquay TQ2 6XA, United Kingdom</address>
                    <capacity>300</capacity>
                    <latitude>50.463301</latitude>
                    <longitude>-3.559394</longitude>
                    <website>https://www.cockingtoncourt.org/</website>
                    <wiki>https://en.wikipedia.org/wiki/Cockington</wiki>
                    <description>A quaint 450 acre country park with scenic garden landscapes, parkland and woodland. Within the vast countryside landscape resides a historic country manor house governed by the Torbay Coast and Countryside Trust.</description>
                    <description_source>https://en.wikipedia.org/wiki/Cockington</description_source>
                    <short_description>Centuries-old country estate.</short_description>
                    <image>https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Cockington_Court_Craft_Centre_-_geograph.org.uk_-_49472.jpg/330px-Cockington_Court_Craft_Centre_-_geograph.org.uk_-_49472.jpg</image>
                    <image_alt>Cockington Court Craft Centre</image_alt>
                    <map_icon>historical_museum.png</map_icon>
                </place_of_interest>
				
                <place_of_interest P_ID="5" category="Beach">
                    <name>Oddicombe beach</name>
                    <address>Babbacombe Downs Rd, Torquay TQ1 3LS, United Kingdom</address>
                    <capacity/>
                    <latitude>50.478308</latitude>
                    <longitude>-3.513335</longitude>
                    <website>https://www.englishriviera.co.uk/things-to-do/oddicombe-beach-torquay-p227603</website>
                    <wiki>https://en.wikipedia.org/wiki/Oddicombe_Beach</wiki>
                    <description>A stunning beach part of the English Riviera UNESCO Global Geopark, that offers fun for all the family. The beach not only offers great views, but also offers watersports, beach shops and a caf√©.</description>
                    <description_source>https://en.wikipedia.org/wiki/Oddicombe_Beach</description_source>
                    <short_description>A popular beach on the english riviera.</short_description>
                    <image>https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Oddicombe.jpg/330px-Oddicombe.jpg</image>
                    <image_alt>Oddicombe Beach from Babbacombe Downs.</image_alt>
                    <map_icon>beach.png</map_icon>
                </place_of_interest>
				
				<place_of_interest P_ID="6" category="Train">
                    <name>Babbacombe Cliff Railway</name>
