=== andrei2timo/TwinCities/DSA-TwinCities/includes/dsa_config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="dsa_config">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="environment"/>
                <xs:element ref="addressing"/>
                <xs:element ref="map_api_key"/>
                <xs:element ref="weather_api_key"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="environment">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="dev" minOccurs="0"/>
                <xs:element ref="live"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="dev" type="connection"/>
    <xs:element name="live" type="connection"/>
    <xs:complexType name="connection">
        <xs:sequence>
            <xs:element ref="base_url"/>
            <xs:element ref="base_path"/>
            <xs:element ref="url_end"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="addressing">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="get_city"/>
                <xs:element ref="get_place_of_interest"/>
                <xs:element ref="images_address"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="get_city" type="xs:string"/>
    <xs:element name="get_place_of_interest" type="xs:string"/>
    <xs:element name="images_address" type="xs:string"/>
    <xs:element name="map_api_key" type="xs:string"/>
    <xs:element name="weather_api_key" type="xs:string"/>
    <xs:element name="base_url" type="xs:anyURI"/>
    <xs:element name="base_path" type="xs:anyURI"/>
    <xs:element name="url_end" type="xs:string"/>
</xs:schema>

=== andrei2timo/TwinCities/DSA-Twin-Cities/includes/dsa_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

#####################################################################
# file    : dsa_config.xml                                          #
# purpose : twin-cities assignment app config file                  #
# author  :                                                         #
# version : 0.1                                                     #
# date    : 10 Jan 2018                                             #
# cities  : Portsmouth & Sydney (City)                              #
#####################################################################

-->

<dsa_config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="dsa_config.xsd">
    <environment>
    <dev>
        <base_url>http://localhost:8080/TwinCities/DSA-Twin-Cities/</base_url>
        <base_path>C:/xampp/php/TwinCities/DSA-Twin-Cities/</base_path>
        <url_end>/</url_end>
    </dev>

    <live>
        <base_url>address</base_url>
        <base_path>address</base_path>
        <url_end>.php</url_end>
    </live>
    </environment>

    <addressing>
        <get_city>city</get_city>
        <get_place_of_interest>interest</get_place_of_interest>
        <images_address>images/</images_address>
    </addressing>

    <map_api_key>AIzaSyA_5RhpGqk3MLa6_dniOSwj2QFuawSSTdY</map_api_key>
    <weather_api_key>793769e7926a4bf2131e3bf791ec2aa2</weather_api_key>
</dsa_config>
